### YamlMime:ManagedReference
items:
- uid: Google.Api.Gax.Grpc.RetrySettings.IJitter
  commentId: T:Google.Api.Gax.Grpc.RetrySettings.IJitter
  id: RetrySettings.IJitter
  parent: Google.Api.Gax.Grpc
  children:
  - Google.Api.Gax.Grpc.RetrySettings.IJitter.GetDelay(System.TimeSpan)
  langs:
  - csharp
  - vb
  name: RetrySettings.IJitter
  nameWithType: RetrySettings.IJitter
  fullName: Google.Api.Gax.Grpc.RetrySettings.IJitter
  type: Interface
  source:
    remote:
      path: src/Google.Api.Gax.Grpc/RetrySettings.cs
      branch: master
      repo: https://github.com/googleapis/gax-dotnet
    id: IJitter
    path: src/Google.Api.Gax.Grpc/RetrySettings.cs
    startLine: 114
  assemblies:
  - Google.Api.Gax.Grpc
  namespace: Google.Api.Gax.Grpc
  summary: "\nProvides a mechanism for applying jitter to delays between retries.\nSee the <xref href=\"Google.Api.Gax.Grpc.RetrySettings.DelayJitter\" data-throw-if-not-resolved=\"false\"></xref> property for more information.\n"
  example: []
  syntax:
    content: public interface IJitter
    content.vb: Public Interface IJitter
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Google.Api.Gax.Grpc.RetrySettings.IJitter.GetDelay(System.TimeSpan)
  commentId: M:Google.Api.Gax.Grpc.RetrySettings.IJitter.GetDelay(System.TimeSpan)
  id: GetDelay(System.TimeSpan)
  parent: Google.Api.Gax.Grpc.RetrySettings.IJitter
  langs:
  - csharp
  - vb
  name: GetDelay(TimeSpan)
  nameWithType: RetrySettings.IJitter.GetDelay(TimeSpan)
  fullName: Google.Api.Gax.Grpc.RetrySettings.IJitter.GetDelay(System.TimeSpan)
  type: Method
  source:
    remote:
      path: src/Google.Api.Gax.Grpc/RetrySettings.cs
      branch: master
      repo: https://github.com/googleapis/gax-dotnet
    id: GetDelay
    path: src/Google.Api.Gax.Grpc/RetrySettings.cs
    startLine: 121
  assemblies:
  - Google.Api.Gax.Grpc
  namespace: Google.Api.Gax.Grpc
  summary: "\nReturns the actual delay to use given a maximum available delay.\n"
  example: []
  syntax:
    content: TimeSpan GetDelay(TimeSpan maxDelay)
    parameters:
    - id: maxDelay
      type: System.TimeSpan
      description: The maximum delay provided by the backoff settings
    return:
      type: System.TimeSpan
      description: The delay to use before retrying.
    content.vb: Function GetDelay(maxDelay As TimeSpan) As TimeSpan
  overload: Google.Api.Gax.Grpc.RetrySettings.IJitter.GetDelay*
references:
- uid: Google.Api.Gax.Grpc.RetrySettings.DelayJitter
  commentId: P:Google.Api.Gax.Grpc.RetrySettings.DelayJitter
- uid: Google.Api.Gax.Grpc
  commentId: N:Google.Api.Gax.Grpc
  isExternal: false
  name: Google.Api.Gax.Grpc
  nameWithType: Google.Api.Gax.Grpc
  fullName: Google.Api.Gax.Grpc
- uid: Google.Api.Gax.Grpc.RetrySettings.IJitter.GetDelay*
  commentId: Overload:Google.Api.Gax.Grpc.RetrySettings.IJitter.GetDelay
  isExternal: false
  name: GetDelay
  nameWithType: RetrySettings.IJitter.GetDelay
  fullName: Google.Api.Gax.Grpc.RetrySettings.IJitter.GetDelay
- uid: System.TimeSpan
  commentId: T:System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
