### YamlMime:ManagedReference
items:
- uid: Google.Api.Gax.Grpc.ServiceSettingsBase
  commentId: T:Google.Api.Gax.Grpc.ServiceSettingsBase
  id: ServiceSettingsBase
  parent: Google.Api.Gax.Grpc
  children:
  - Google.Api.Gax.Grpc.ServiceSettingsBase.#ctor
  - Google.Api.Gax.Grpc.ServiceSettingsBase.#ctor(Google.Api.Gax.Grpc.ServiceSettingsBase)
  - Google.Api.Gax.Grpc.ServiceSettingsBase.CallSettings
  - Google.Api.Gax.Grpc.ServiceSettingsBase.Clock
  - Google.Api.Gax.Grpc.ServiceSettingsBase.Scheduler
  langs:
  - csharp
  - vb
  name: ServiceSettingsBase
  nameWithType: ServiceSettingsBase
  fullName: Google.Api.Gax.Grpc.ServiceSettingsBase
  type: Class
  source:
    remote:
      path: src/Google.Api.Gax.Grpc/ServiceSettingsBase.cs
      branch: master
      repo: https://github.com/googleapis/gax-dotnet
    id: ServiceSettingsBase
    path: src/Google.Api.Gax.Grpc/ServiceSettingsBase.cs
    startLine: 15
  assemblies:
  - Google.Api.Gax.Grpc
  namespace: Google.Api.Gax.Grpc
  summary: "\nCommon settings for all services.\n"
  example: []
  syntax:
    content: public abstract class ServiceSettingsBase
    content.vb: Public MustInherit Class ServiceSettingsBase
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - abstract
  - class
  modifiers.vb:
  - Public
  - MustInherit
  - Class
- uid: Google.Api.Gax.Grpc.ServiceSettingsBase.#ctor
  commentId: M:Google.Api.Gax.Grpc.ServiceSettingsBase.#ctor
  id: '#ctor'
  parent: Google.Api.Gax.Grpc.ServiceSettingsBase
  langs:
  - csharp
  - vb
  name: ServiceSettingsBase()
  nameWithType: ServiceSettingsBase.ServiceSettingsBase()
  fullName: Google.Api.Gax.Grpc.ServiceSettingsBase.ServiceSettingsBase()
  type: Constructor
  source:
    remote:
      path: src/Google.Api.Gax.Grpc/ServiceSettingsBase.cs
      branch: master
      repo: https://github.com/googleapis/gax-dotnet
    id: .ctor
    path: src/Google.Api.Gax.Grpc/ServiceSettingsBase.cs
    startLine: 21
  assemblies:
  - Google.Api.Gax.Grpc
  namespace: Google.Api.Gax.Grpc
  summary: "\nConstructs a new service settings base object with a default version header, unset call settings and\nunset clock.\n"
  example: []
  syntax:
    content: protected ServiceSettingsBase()
    content.vb: Protected Sub New
  overload: Google.Api.Gax.Grpc.ServiceSettingsBase.#ctor*
  modifiers.csharp:
  - protected
  modifiers.vb:
  - Protected
- uid: Google.Api.Gax.Grpc.ServiceSettingsBase.#ctor(Google.Api.Gax.Grpc.ServiceSettingsBase)
  commentId: M:Google.Api.Gax.Grpc.ServiceSettingsBase.#ctor(Google.Api.Gax.Grpc.ServiceSettingsBase)
  id: '#ctor(Google.Api.Gax.Grpc.ServiceSettingsBase)'
  parent: Google.Api.Gax.Grpc.ServiceSettingsBase
  langs:
  - csharp
  - vb
  name: ServiceSettingsBase(ServiceSettingsBase)
  nameWithType: ServiceSettingsBase.ServiceSettingsBase(ServiceSettingsBase)
  fullName: Google.Api.Gax.Grpc.ServiceSettingsBase.ServiceSettingsBase(Google.Api.Gax.Grpc.ServiceSettingsBase)
  type: Constructor
  source:
    remote:
      path: src/Google.Api.Gax.Grpc/ServiceSettingsBase.cs
      branch: master
      repo: https://github.com/googleapis/gax-dotnet
    id: .ctor
    path: src/Google.Api.Gax.Grpc/ServiceSettingsBase.cs
    startLine: 36
  assemblies:
  - Google.Api.Gax.Grpc
  namespace: Google.Api.Gax.Grpc
  summary: "\nConstructs a new service settings base object by cloning the settings from an existing one.\n"
  example: []
  syntax:
    content: protected ServiceSettingsBase(ServiceSettingsBase existing)
    parameters:
    - id: existing
      type: Google.Api.Gax.Grpc.ServiceSettingsBase
      description: The existing settings object to clone settings from. Must not be null.
    content.vb: Protected Sub New(existing As ServiceSettingsBase)
  overload: Google.Api.Gax.Grpc.ServiceSettingsBase.#ctor*
  modifiers.csharp:
  - protected
  modifiers.vb:
  - Protected
- uid: Google.Api.Gax.Grpc.ServiceSettingsBase.CallSettings
  commentId: P:Google.Api.Gax.Grpc.ServiceSettingsBase.CallSettings
  id: CallSettings
  parent: Google.Api.Gax.Grpc.ServiceSettingsBase
  langs:
  - csharp
  - vb
  name: CallSettings
  nameWithType: ServiceSettingsBase.CallSettings
  fullName: Google.Api.Gax.Grpc.ServiceSettingsBase.CallSettings
  type: Property
  source:
    remote:
      path: src/Google.Api.Gax.Grpc/ServiceSettingsBase.cs
      branch: master
      repo: https://github.com/googleapis/gax-dotnet
    id: CallSettings
    path: src/Google.Api.Gax.Grpc/ServiceSettingsBase.cs
    startLine: 51
  assemblies:
  - Google.Api.Gax.Grpc
  namespace: Google.Api.Gax.Grpc
  summary: "\nIf not null, <xref href=\"Google.Api.Gax.Grpc.ServiceSettingsBase.CallSettings\" data-throw-if-not-resolved=\"false\"></xref> that are applied to every RPC performed by the client.\nIf null or unset, RPC default settings will be used for all settings.\n"
  example: []
  syntax:
    content: public CallSettings CallSettings { get; set; }
    parameters: []
    return:
      type: Google.Api.Gax.Grpc.CallSettings
    content.vb: Public Property CallSettings As CallSettings
  overload: Google.Api.Gax.Grpc.ServiceSettingsBase.CallSettings*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Google.Api.Gax.Grpc.ServiceSettingsBase.Clock
  commentId: P:Google.Api.Gax.Grpc.ServiceSettingsBase.Clock
  id: Clock
  parent: Google.Api.Gax.Grpc.ServiceSettingsBase
  langs:
  - csharp
  - vb
  name: Clock
  nameWithType: ServiceSettingsBase.Clock
  fullName: Google.Api.Gax.Grpc.ServiceSettingsBase.Clock
  type: Property
  source:
    remote:
      path: src/Google.Api.Gax.Grpc/ServiceSettingsBase.cs
      branch: master
      repo: https://github.com/googleapis/gax-dotnet
    id: Clock
    path: src/Google.Api.Gax.Grpc/ServiceSettingsBase.cs
    startLine: 60
  assemblies:
  - Google.Api.Gax.Grpc
  namespace: Google.Api.Gax.Grpc
  summary: "\nIf not null, the clock used to calculate RPC deadlines. If null or unset, the <xref href=\"Google.Api.Gax.SystemClock\" data-throw-if-not-resolved=\"false\"></xref> is used.\n"
  remarks: "\nThis is primarily only to be set for testing.\nIn production code generally leave this unset to use the <xref href=\"Google.Api.Gax.SystemClock\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  example: []
  syntax:
    content: public IClock Clock { get; set; }
    parameters: []
    return:
      type: Google.Api.Gax.IClock
    content.vb: Public Property Clock As IClock
  overload: Google.Api.Gax.Grpc.ServiceSettingsBase.Clock*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Google.Api.Gax.Grpc.ServiceSettingsBase.Scheduler
  commentId: P:Google.Api.Gax.Grpc.ServiceSettingsBase.Scheduler
  id: Scheduler
  parent: Google.Api.Gax.Grpc.ServiceSettingsBase
  langs:
  - csharp
  - vb
  name: Scheduler
  nameWithType: ServiceSettingsBase.Scheduler
  fullName: Google.Api.Gax.Grpc.ServiceSettingsBase.Scheduler
  type: Property
  source:
    remote:
      path: src/Google.Api.Gax.Grpc/ServiceSettingsBase.cs
      branch: master
      repo: https://github.com/googleapis/gax-dotnet
    id: Scheduler
    path: src/Google.Api.Gax.Grpc/ServiceSettingsBase.cs
    startLine: 70
  assemblies:
  - Google.Api.Gax.Grpc
  namespace: Google.Api.Gax.Grpc
  summary: "\nIf not null, the scheduler used for delays between operations (e.g. for retry).\nIf null or unset, the <xref href=\"Google.Api.Gax.SystemScheduler\" data-throw-if-not-resolved=\"false\"></xref> is used.\n"
  remarks: "\nThis is primarily only to be set for testing.\nIn production code generally leave this unset to use the <xref href=\"Google.Api.Gax.SystemScheduler\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  example: []
  syntax:
    content: public IScheduler Scheduler { get; set; }
    parameters: []
    return:
      type: Google.Api.Gax.IScheduler
    content.vb: Public Property Scheduler As IScheduler
  overload: Google.Api.Gax.Grpc.ServiceSettingsBase.Scheduler*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Google.Api.Gax.Grpc
  commentId: N:Google.Api.Gax.Grpc
  isExternal: false
  name: Google.Api.Gax.Grpc
  nameWithType: Google.Api.Gax.Grpc
  fullName: Google.Api.Gax.Grpc
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Google.Api.Gax.Grpc.ServiceSettingsBase.#ctor*
  commentId: Overload:Google.Api.Gax.Grpc.ServiceSettingsBase.#ctor
  isExternal: false
  name: ServiceSettingsBase
  nameWithType: ServiceSettingsBase.ServiceSettingsBase
  fullName: Google.Api.Gax.Grpc.ServiceSettingsBase.ServiceSettingsBase
- uid: Google.Api.Gax.Grpc.ServiceSettingsBase
  commentId: T:Google.Api.Gax.Grpc.ServiceSettingsBase
  parent: Google.Api.Gax.Grpc
  isExternal: false
  name: ServiceSettingsBase
  nameWithType: ServiceSettingsBase
  fullName: Google.Api.Gax.Grpc.ServiceSettingsBase
- uid: Google.Api.Gax.Grpc.ServiceSettingsBase.CallSettings
  commentId: P:Google.Api.Gax.Grpc.ServiceSettingsBase.CallSettings
- uid: Google.Api.Gax.Grpc.ServiceSettingsBase.CallSettings*
  commentId: Overload:Google.Api.Gax.Grpc.ServiceSettingsBase.CallSettings
  isExternal: false
  name: CallSettings
  nameWithType: ServiceSettingsBase.CallSettings
  fullName: Google.Api.Gax.Grpc.ServiceSettingsBase.CallSettings
- uid: Google.Api.Gax.Grpc.CallSettings
  commentId: T:Google.Api.Gax.Grpc.CallSettings
  parent: Google.Api.Gax.Grpc
  isExternal: false
  name: CallSettings
  nameWithType: CallSettings
  fullName: Google.Api.Gax.Grpc.CallSettings
- uid: Google.Api.Gax.SystemClock
  commentId: T:Google.Api.Gax.SystemClock
- uid: Google.Api.Gax.Grpc.ServiceSettingsBase.Clock*
  commentId: Overload:Google.Api.Gax.Grpc.ServiceSettingsBase.Clock
  isExternal: false
  name: Clock
  nameWithType: ServiceSettingsBase.Clock
  fullName: Google.Api.Gax.Grpc.ServiceSettingsBase.Clock
- uid: Google.Api.Gax.IClock
  commentId: T:Google.Api.Gax.IClock
  parent: Google.Api.Gax
  isExternal: false
  name: IClock
  nameWithType: IClock
  fullName: Google.Api.Gax.IClock
- uid: Google.Api.Gax
  commentId: N:Google.Api.Gax
  isExternal: false
  name: Google.Api.Gax
  nameWithType: Google.Api.Gax
  fullName: Google.Api.Gax
- uid: Google.Api.Gax.SystemScheduler
  commentId: T:Google.Api.Gax.SystemScheduler
- uid: Google.Api.Gax.Grpc.ServiceSettingsBase.Scheduler*
  commentId: Overload:Google.Api.Gax.Grpc.ServiceSettingsBase.Scheduler
  isExternal: false
  name: Scheduler
  nameWithType: ServiceSettingsBase.Scheduler
  fullName: Google.Api.Gax.Grpc.ServiceSettingsBase.Scheduler
- uid: Google.Api.Gax.IScheduler
  commentId: T:Google.Api.Gax.IScheduler
  parent: Google.Api.Gax
  isExternal: false
  name: IScheduler
  nameWithType: IScheduler
  fullName: Google.Api.Gax.IScheduler
